### ISSUE TITLE
部分词库转换失败

### ISSUE THREAD

**Issue by Aleksanaa** [thisiswangle/scel2txt#1]
“网络流行新词【官方推荐】.scel”没有转换（一共放了七个scel文件），输出如下：

--------------------------------------------------------------------------------
数学词汇大全【官方推荐】.scel:15992 个词
--------------------------------------------------------------------------------
中国高等院校（大学）大全【官方推荐】.scel:7192 个词
--------------------------------------------------------------------------------
物理词汇大全【官方推荐】.scel:13107 个词
--------------------------------------------------------------------------------
计算机词汇大全【官方推荐】.scel:10300 个词
--------------------------------------------------------------------------------
开发大神专用词库【官方推荐】.scel:430 个词
--------------------------------------------------------------------------------
linux少量术语.scel:136 个词
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "scel2txt.py", line 175, in <module>
    scel2txt.deal(os.path.join("./scel", scel_file))
  File "scel2txt.py", line 147, in deal
    self.getChinese(data[self.startChinese:])
  File "scel2txt.py", line 116, in getChinese
    py = self.getWordPy(data[pos: pos+py_table_len])
  File "scel2txt.py", line 87, in getWordPy
    ret.append(self.GPy_Table[index])
KeyError: 34945

**Comment by Aleksanaa** [comment]
补充一下：自动合并功能也没有生效

**Comment by lewangdev** [comment]
`网络流行新词【官方推荐】.scel于2020-03-22 17:04:27发布的第4396个版本` 词库按照网上格式解析似乎有些问题，无法解析的词条忽略掉 10 条，目前共计 24923
